_target_: tracklab.wrappers.detect_single.topdown_mmpose_api.TopDownMMPose
config_name: td-hm_hrnet-w32_8xb64-20e_posetrack18-256x192 # total : 83.0
#config_name: topdown_heatmap_hrnet_w32_posetrack18_384x288 # total : 83.6
#config_name: topdown_heatmap_hrnet_w48_posetrack18_256x192 # total : 84.4
#config_name: topdown_heatmap_hrnet_w48_posetrack18_384x288 # total : 84.5
path_to_checkpoint: ${model_dir}/mmpose/${.config_name}.pth
vis_kp_threshold: 0.1
batch_size: 2
