_target_: tracklab.wrappers.MOT20Evaluator

test_set: "train"

cfg:
  eval_mot: True

  bbox_column_for_eval: "bbox_ltwh"  # which bbox column to use for evaluation: {"bbox_ltwh", "track_bbox_kf_ltwh", ...}

  mot_trackers_folder: "eval/mot20"
  mot_gt_folder: ${dataset.dataset_path}/train
